name: Repo action
on:
  push:
    branches:
      - '*/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-pkg-cache: true
          skip-build-cache: true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
         go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test cover
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov